services:
  db:
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: postgres
    network_mode: host
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgres/

  db-prom-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    network_mode: host
    environment:
      DATA_SOURCE_URI: "localhost:5432/postgres?sslmode=disable" 
      DATA_SOURCE_USER: postgres 
      DATA_SOURCE_PASS: postgres 
    ports:
      - 9187:9187

  prometheus:
    image: prom/prometheus:v3-distroless
    network_mode: host
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus.yaml
