scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  - job_name: postgres-exporter
    static_configs:
      - targets:
          - "db-prom-exporter:9187"
